apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gateway-upgrade-pvc
  namespace: extension-gateway
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: batch/v1
kind: Job
metadata:
  name: gateway-upgrade-job
  namespace: extension-gateway
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: upgrade-tool
          image: wenhaozhou/gateway-upgrade-tool:v0.0.1
          imagePullPolicy: Always
          args:
            - "upgrade"
            - "--gateways=*"
            - "--need-backup=true"
          volumeMounts:
            - name: backup-volume
              mountPath: /mnt/backup
      serviceAccountName: gateway-agent-backend
      volumes:
        - name: backup-volume
          persistentVolumeClaim:
            claimName: gateway-upgrade-pvc
