name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: wenhaozhou
  IMAGE_NAME: gateway-upgrade-tool
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract metadata
      id: meta
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG=${GITHUB_REF#refs/heads/}
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.event_name == 'push'
      uses: docker/login-action@v3
      with:
        registry: ${{ env.IMAGE_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push docker images
      if: github.event_name == 'push'
      run: |
        REPO=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}
        TAG=${{ steps.meta.outputs.tag }}
        echo "Building and pushing ${REPO}:${TAG}"
        docker buildx build --platform ${{ env.PLATFORMS }} -t ${REPO}:${TAG} --push .
