name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]

env:
  IMAGE_REGISTRY: docker.io
  IMAGE_NAMESPACE: wenhaozhou
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Extract metadata
      id: meta
      run: |
        if [[ $GITHUB_REF == refs/tags/* ]]; then
          TAG=${GITHUB_REF#refs/tags/}
        else
          TAG=${GITHUB_REF#refs/heads/}
        fi
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        echo "Generated tag: $TAG"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push docker images
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name == 'push'
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ env.IMAGE_REGISTRY }}
        REPO=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAMESPACE }}
        TAG=${{ steps.meta.outputs.tag }}
        echo "Building and pushing ${REPO}:${TAG}"
        docker buildx build --platform ${{ env.PLATFORMS }} -t ${REPO}:${TAG} --push .
